version: '3.8'

services:
  webapp:
    image: api_uts_net:v1.0
    container_name: api-uts-net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5000"
    volumes:
      - ./ApiUtsNet:/app
